(()=>{`use strict`;
const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,`0`)}-${String(date.getDate()).padStart(2,`0`)}`;
document.querySelectorAll(`input[type="number"]`).forEach(input=>input.setAttribute(`inputmode`,input.step===`1`?`numeric`:`decimal`));
document.querySelectorAll(`input[type="date"]`).forEach(input=>{const label=input.closest(`label`);if(!label)return;const field=input.closest(`.dateField`),bar=document.createElement(`div`);bar.className=`dateQuickActions`;bar.setAttribute(`role`,`group`);bar.setAttribute(`aria-label`,`تواريخ سريعة`);for(const [title,mode] of [[`اليوم`,`today`],[`أمس`,`yesterday`],[`أول الشهر`,`first`]]){if(mode===`first`&&field?.querySelector(`button`))continue;const button=document.createElement(`button`);button.type=`button`;button.className=`btn ghost small`;button.textContent=title;button.addEventListener(`click`,()=>{const date=new Date();if(mode===`yesterday`)date.setDate(date.getDate()-1);if(mode===`first`)date.setDate(1);input.value=iso(date);input.dispatchEvent(new Event(`input`,{bubbles:true}));input.dispatchEvent(new Event(`change`,{bubbles:true}));window.dispatchEvent(new Event(`salary:render`))});bar.append(button)}if(field){const existing=field.querySelector(`button`);if(existing)bar.append(existing);field.append(bar)}else label.after(bar)});
const aliases={[`Arab Bank`]:`العربي`,Reflect:`ريفلكت`,Etihad:`الاتحاد`,[`Zain Cash`]:`زين كاش`,Blink:`بلينك`,Rajihi:`الراجحي`,[`Jordan Bank`]:`بنك الأردن`,Qawn:`قون`,[`U Wallet`]:`يو والت`};
function labels(){document.querySelectorAll(`select option`).forEach(option=>{const arabic=aliases[option.value];if(arabic&&option.textContent.includes(option.value))option.textContent=option.textContent.replace(option.value,arabic)})}
const spies=[];
function createSpy(pageId,entries){const page=document.getElementById(pageId);if(!page)return;const nav=document.createElement(`nav`);nav.className=`sectionSpy`;nav.setAttribute(`aria-label`,`أقسام الصفحة`);const sections=[];entries.forEach(([selector,title],i)=>{const element=page.querySelector(selector);if(!element)return;element.id||=`${pageId}Section${i}`;element.classList.add(`spySection`);const button=document.createElement(`button`);button.type=`button`;button.textContent=title;button.addEventListener(`click`,()=>{element.scrollIntoView({behavior:matchMedia(`(prefers-reduced-motion: reduce)`).matches?`auto`:`smooth`,block:`start`})});nav.append(button);sections.push({element,button})});if(!sections.length)return;page.prepend(nav);spies.push({page,nav,sections});if(typeof IntersectionObserver!==`undefined`){const observer=new IntersectionObserver(update,{rootMargin:`-15% 0px -65% 0px`});sections.forEach(({element})=>observer.observe(element))}}
createSpy(`settingsPage`,[[`.installCard`,`التطبيق`],[`.settingCard:nth-child(1)`,`الهوية`],[`.settingCard:nth-child(2)`,`المظهر`],[`.settingCard:nth-child(3)`,`السلوك`],[`.settingCard:nth-child(4)`,`النسخ الاحتياطي`],[`#cloudSettingCard`,`السحابة`]]);
createSpy(`categoriesPage`,[[`#categoryMetrics`,`الملخص`],[`.decisionGrid article:nth-child(1)`,`التوزيع`],[`.decisionGrid article:nth-child(2)`,`التحليل`],[`#categoryCards`,`التصنيفات`],[`.recurrenceSection`,`التكرارات`]]);
let scheduled=false;function update(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;for(const spy of spies){if(!spy.page.classList.contains(`active`))continue;const line=spy.nav.getBoundingClientRect().bottom+24;let current=spy.sections[0];for(const section of spy.sections){section.element.style.scrollMarginTop=`${spy.nav.offsetHeight+30}px`;if(section.element.getBoundingClientRect().top<=line)current=section}for(const {button} of spy.sections){const active=button===current.button;button.classList.toggle(`active`,active);if(active)button.setAttribute(`aria-current`,`location`);else button.removeAttribute(`aria-current`)}}})}
window.addEventListener(`salary:render`,()=>{labels();update()});document.addEventListener(`scroll`,update,{passive:true});window.addEventListener(`resize`,update);document.addEventListener(`click`,update);labels();update();
})();
