(()=>{`use strict`;const color=document.getElementById(`settingAccent`);color?.addEventListener(`input`,()=>document.documentElement.style.setProperty(`--accent`,color.value));const menu=document.getElementById(`mobileMore`),toggle=document.getElementById(`mobileMoreBtn`),closeButton=document.getElementById(`closeMoreBtn`);let priorFocus;function closeMenu(){if(menu.classList.contains(`hidden`))return;menu.classList.add(`hidden`);document.body.classList.remove(`menuOpen`);toggle.setAttribute(`aria-expanded`,`false`);priorFocus?.focus()}function openMenu(){priorFocus=document.activeElement;menu.classList.remove(`hidden`);document.body.classList.add(`menuOpen`);toggle.setAttribute(`aria-expanded`,`true`);closeButton.focus()}toggle.addEventListener(`click`,()=>menu.classList.contains(`hidden`)?openMenu():closeMenu());closeButton.addEventListener(`click`,closeMenu);menu.addEventListener(`click`,ev=>{if(ev.target===menu||ev.target.closest(`[data-go]`))closeMenu()});document.addEventListener(`keydown`,ev=>{if(menu.classList.contains(`hidden`))return;if(ev.key===`Escape`){ev.preventDefault();closeMenu()}if(ev.key===`Tab`){const nodes=[...menu.querySelectorAll(`button,a[href]`)],first=nodes[0],last=nodes[nodes.length-1];if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus()}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus()}}});window.addEventListener(`resize`,()=>{if(window.innerWidth>760)closeMenu()})})();
(()=>{
  `use strict`;
  const all=[],popup=document.createElement(`div`);
  popup.id=`autocompleteOptions`;popup.className=`comboPopup hidden`;popup.setAttribute(`role`,`listbox`);document.body.append(popup);
  let active=null,index=-1,results=[],sequence=0,syncTimer;
  const names={monthInput:`الشهر`,txType:`نوع الحركة`,txCategory:`التصنيف`,txAccount:`الحساب`,txRecurring:`التكرار`,txStatus:`حالة الحركة`,reportFrom:`من شهر`,reportTo:`إلى شهر`,reportCategory:`التصنيف`,reportAccount:`الحساب`,reportStatus:`الحالة`,dateMonth:`الأشهر`,dateType:`النوع`,dateStatus:`الحالة`,transferStatus:`حالة الحوالة`,categoryFrom:`من شهر`,categoryTo:`إلى شهر`,categoryNameFilter:`التصنيف`,categoryAccount:`الحساب`,categoryType:`نوع الحركة`,categoryStatus:`الحالة`,categoryVisibility:`التصنيفات النشطة والمؤرشفة`};
  const escape=value=>String(value??``).replace(/[&<>"']/g,c=>({[`&`]:`&amp;`,[`<`]:`&lt;`,[`>`]:`&gt;`,[`"`]:`&quot;`,[`'`]:`&#39;`})[c]);
  const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,`0`)}-${String(date.getDate()).padStart(2,`0`)}`;
  function parseTyped(value,type){value=value.trim().replace(/[٠-٩]/g,d=>String(`٠١٢٣٤٥٦٧٨٩`.indexOf(d))).replace(/[۰-۹]/g,d=>String(`۰۱۲۳۴۵۶۷۸۹`.indexOf(d)));if(type===`date`&&/^\d{1,2}[\/.-]\d{1,2}[\/.-]\d{4}$/.test(value)){const [day,month,year]=value.split(/[\/.-]/);value=`${year}-${month.padStart(2,`0`)}-${day.padStart(2,`0`)}`}if(type===`month`){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(value)||value.startsWith(`0000`))return null;return value}if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||value.startsWith(`0000`))return null;const date=new Date(`${value}T12:00:00`);return Number.isFinite(+date)&&iso(date)===value?value:null}
  function values(combo){const control=combo.control;if(combo.type===`select`)return [...control.options].filter(option=>!option.disabled&&option.value!==``).map(option=>({value:option.value,label:option.textContent.trim()}));const today=iso(new Date()),pivot=parseTyped(control.value,combo.type)||today.slice(0,combo.type===`month`?7:10),months=new Set([today.slice(0,7)]);try{Object.entries(JSON.parse(localStorage.getItem(`salary_manager_v2`)||`{}`).months||{}).filter(([key,data])=>/^\d{4}-(0[1-9]|1[0-2])$/.test(key)&&((data.items||[]).length||(data.transfers||[]).length)).forEach(([month])=>months.add(month))}catch{}const year=Number(pivot.slice(0,4)),month=Number(pivot.slice(5,7))-1;if(combo.type===`month`)return [...months].sort().map(value=>({value,label:`${value} · ${new Intl.DateTimeFormat(`ar-EG`,{month:`long`,year:`numeric`}).format(new Date(`${value}-01T12:00:00`))}`}));const dates=new Set([today,`${today.slice(0,7)}-01`]);if(control.value)dates.add(control.value);for(let offset=-1;offset<=1;offset++){const first=new Date(year,month+offset,1,12),last=new Date(first.getFullYear(),first.getMonth()+1,0,12).getDate();for(let day=1;day<=last;day++)dates.add(iso(new Date(first.getFullYear(),first.getMonth(),day,12)))}return [...dates].sort().map(value=>({value,label:`${value}${value===today?` · اليوم`:value.endsWith(`-01`)?` · أول الشهر`:``} · ${new Intl.DateTimeFormat(`ar-EG`,{weekday:`long`,day:`numeric`,month:`long`}).format(new Date(`${value}T12:00:00`))}`}))}
  function display(combo){if(combo.type===`select`)return combo.control.selectedOptions[0]?.textContent.trim()||``;return combo.control.value}
  function closePopup(){if(active){active.input.setAttribute(`aria-expanded`,`false`);active.input.removeAttribute(`aria-activedescendant`)}active=null;index=-1;results=[];popup.classList.add(`hidden`)}
  function position(){if(!active)return;const rect=active.wrapper.getBoundingClientRect(),height=Math.min(280,window.innerHeight-24),below=window.innerHeight-rect.bottom-12;popup.style.width=`${Math.max(180,Math.min(rect.width,window.innerWidth-24))}px`;popup.style.left=`${Math.max(12,Math.min(rect.left,window.innerWidth-parseFloat(popup.style.width)-12))}px`;popup.style.maxHeight=`${Math.max(100,Math.min(height,below>=150?below:rect.top-12))}px`;popup.style.top=below>=150?`${rect.bottom+6}px`:`auto`;popup.style.bottom=below>=150?`auto`:`${window.innerHeight-rect.top+6}px`}
  function render(query=``){if(!active)return;const search=query.trim().toLocaleLowerCase(`ar`);results=values(active).filter(option=>`${option.label} ${option.value}`.toLocaleLowerCase(`ar`).includes(search));index=results.length?Math.max(0,query?0:results.findIndex(option=>option.value===active.control.value)):-1;if(!results.length)active.input.removeAttribute(`aria-activedescendant`);popup.innerHTML=results.length?results.map((option,i)=>`<button type="button" role="option" id="comboOption${i}" data-combo-index="${i}" aria-selected="${i===index}" class="comboOption${option.value===active.control.value?` selected`:``}"><span>${escape(option.label)}</span>${option.value===active.control.value?`<span aria-hidden="true">✓</span>`:``}</button>`).join(``):`<div class="comboEmpty">${active.type===`month`?`لا توجد حركات في هذا الشهر. اختر شهرا من القائمة.`:active.type===`select`?`لا توجد نتائج مطابقة`:`لا توجد اقتراحات مطابقة. يمكنك إدخال تاريخ صحيح مباشرة.`}</div>`;popup.classList.remove(`hidden`);active.input.setAttribute(`aria-expanded`,`true`);updateHighlight();position()}
  function updateHighlight(){popup.querySelectorAll(`[data-combo-index]`).forEach((node,i)=>{node.classList.toggle(`highlighted`,i===index);node.setAttribute(`aria-selected`,String(i===index));if(i===index){active?.input.setAttribute(`aria-activedescendant`,node.id);node.scrollIntoView?.({block:`nearest`})}})}
  function openPopup(combo){if(combo.control.disabled)return;if(active!==combo)closePopup();active=combo;render(``)}
  function commit(combo,value){combo.control.value=value;if(combo.control.value!==value)return false;combo.input.value=display(combo);combo.input.setCustomValidity(``);combo.dirty=false;closePopup();combo.control.dispatchEvent(new Event(`input`,{bubbles:true}));combo.control.dispatchEvent(new Event(`change`,{bubbles:true}));syncAll();return true}
  function direct(combo){const raw=combo.input.value.trim();if(!raw&&!combo.control.required)return commit(combo,``);if(combo.type!==`select`){const parsed=parseTyped(raw,combo.type);if(parsed&&(combo.type!==`month`||values(combo).some(option=>option.value===parsed)))return commit(combo,parsed)}else{const found=values(combo).find(option=>option.label===raw||option.value===raw);if(found)return commit(combo,found.value)}return false}
  function sync(combo,force=false){if(combo.lastValue!==undefined&&combo.lastValue!==combo.control.value){combo.dirty=false;force=true}combo.lastValue=combo.control.value;combo.input.disabled=combo.control.disabled;combo.input.required=combo.control.required;combo.wrapper.classList.toggle(`disabled`,combo.control.disabled);if(force||(!combo.dirty&&document.activeElement!==combo.input)){combo.input.value=display(combo);combo.input.setCustomValidity(``)}if(!combo.dirty&&document.activeElement===combo.input)combo.input.value=display(combo)}
  function syncAll(){all.forEach(combo=>sync(combo))}
  function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(syncAll,0)}
  document.querySelectorAll(`select,input[type="date"],input[type="month"]`).forEach(control=>{
    const type=control.tagName===`SELECT`?`select`:control.type,label=control.closest(`label`)?.querySelector(`span`)?.textContent||control.getAttribute(`aria-label`)||names[control.id]||control.getAttribute(`placeholder`)||`اختر أو ابحث`,wrapper=document.createElement(`div`),input=document.createElement(`input`),chevron=document.createElement(`span`);
    wrapper.className=`searchCombo`;input.type=`text`;input.id=`searchable_${control.id||++sequence}`;input.className=`comboInput`;input.autocomplete=`off`;input.setAttribute(`role`,`combobox`);input.setAttribute(`aria-autocomplete`,`list`);input.setAttribute(`aria-expanded`,`false`);input.setAttribute(`aria-controls`,popup.id);input.setAttribute(`aria-label`,label);input.placeholder=type===`select`?`ابحث في ${label}...`:type===`date`?`ابحث أو اكتب YYYY-MM-DD`:`ابحث أو اكتب YYYY-MM`;if(type!==`select`)input.dir=`ltr`;
    chevron.className=`comboChevron`;chevron.setAttribute(`aria-hidden`,`true`);chevron.innerHTML=`<svg class="uiIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="m7 10 5 5 5-5"/></svg>`;
    control.before(wrapper);wrapper.append(input,chevron,control);if(type===`month`&&control.closest(`.toolbar`)){const caption=document.createElement(`span`);caption.className=`comboCaption`;caption.textContent=label;wrapper.prepend(caption);wrapper.classList.add(`labelledCombo`)}control.classList.add(`nativeComboControl`);control.tabIndex=-1;control.setAttribute(`aria-hidden`,`true`);const combo={control,input,wrapper,type,dirty:false};all.push(combo);sync(combo,true);
    input.addEventListener(`focus`,()=>{openPopup(combo);input.select()});input.addEventListener(`click`,()=>{if(active!==combo)openPopup(combo)});input.addEventListener(`input`,()=>{combo.dirty=true;input.setCustomValidity(type===`select`?`اختر نتيجة من القائمة`:type===`date`?`أدخل تاريخا صحيحا أو اختر اقتراحا`:`أدخل شهرا صحيحا أو اختر اقتراحا`);active=combo;render(input.value)});
    input.addEventListener(`keydown`,ev=>{if([`ArrowDown`,`ArrowUp`].includes(ev.key)){ev.preventDefault();if(active!==combo)openPopup(combo);else if(results.length){index=(index+(ev.key===`ArrowDown`?1:-1)+results.length)%results.length;updateHighlight()}}else if(ev.key===`Enter`&&active===combo){ev.preventDefault();if(!direct(combo)&&index>=0)commit(combo,results[index].value)}else if(ev.key===`Escape`&&active===combo){ev.preventDefault();ev.stopPropagation();combo.dirty=false;sync(combo,true);closePopup()}else if(ev.key===`Tab`){if(combo.dirty)direct(combo);closePopup()}});
    input.addEventListener(`blur`,()=>{if(combo.dirty)direct(combo);setTimeout(()=>{if(active===combo&&document.activeElement!==input)closePopup()},0)});control.addEventListener(`focus`,()=>input.focus());control.addEventListener(`input`,()=>{combo.dirty=false;sync(combo,true)});control.addEventListener(`change`,()=>{combo.dirty=false;sync(combo,true)});control.addEventListener(`invalid`,ev=>{ev.preventDefault();input.focus();input.setCustomValidity(`اختر قيمة صحيحة`);input.reportValidity()});
    new MutationObserver(()=>{sync(combo);if(active===combo&&!combo.dirty)render(``)}).observe(control,{childList:true,subtree:true,attributes:true,attributeFilter:[`disabled`,`required`,`value`,`selected`]});
  });
  document.querySelectorAll(`.modal`).forEach(modal=>new MutationObserver(()=>{all.filter(combo=>modal.contains(combo.control)).forEach(combo=>{combo.dirty=false;sync(combo,true)});if(active&&modal.contains(active.control))closePopup()}).observe(modal,{attributes:true,attributeFilter:[`class`]}));
  popup.addEventListener(`mousedown`,ev=>ev.preventDefault());popup.addEventListener(`click`,ev=>{const option=ev.target.closest(`[data-combo-index]`);if(option&&active)commit(active,results[Number(option.dataset.comboIndex)].value)});
  document.addEventListener(`click`,ev=>{if(active&&!active.wrapper.contains(ev.target)&&!popup.contains(ev.target))closePopup();scheduleSync()});document.addEventListener(`change`,scheduleSync);window.addEventListener(`salary:render`,scheduleSync);window.addEventListener(`resize`,position);document.addEventListener(`scroll`,ev=>{if(active&&!popup.contains(ev.target))position()},true);
  document.addEventListener(`submit`,ev=>{for(const combo of all){if(combo.input.form!==ev.target||combo.input.disabled||combo.input.closest(`.hidden`))continue;if(combo.dirty&&!direct(combo)){ev.preventDefault();combo.input.reportValidity();return}}},true);
})();


(()=>{ `use strict`;document.querySelectorAll(`.toolbar`).forEach((toolbar,index)=>{const group=document.createElement(`div`),button=document.createElement(`button`);group.className=`mobileFilterGroup mobileFiltersCollapsed`;button.type=`button`;button.className=`mobileFilterToggle`;button.textContent=`البحث والفلاتر`;toolbar.id||=(`mobileFilters${index}`);button.setAttribute(`aria-controls`,toolbar.id);button.setAttribute(`aria-expanded`,`false`);toolbar.before(group);group.append(button,toolbar);const chips=group.nextElementSibling;if(chips?.classList.contains(`filterChips`))group.append(chips);button.addEventListener(`click`,()=>{const open=group.classList.toggle(`mobileFiltersCollapsed`)===false;button.setAttribute(`aria-expanded`,String(open))})});})();

(()=>{`use strict`;function placeCloud(){const pill=document.getElementById(`moneyCloudPill`),settings=document.getElementById(`settingsPage`);if(!pill||!settings)return false;let card=document.getElementById(`cloudSettingCard`);if(!card){card=document.createElement(`article`);card.id=`cloudSettingCard`;card.className=`panel cloudSettingCard`;card.innerHTML=`<h2>المزامنة السحابية</h2><p>بياناتك تتزامن تلقائيا عند ربط الحساب. يمكنك إدارة الربط من هنا.</p>`;const install=settings.querySelector(`.installCard`);install?install.after(card):settings.prepend(card)}card.append(pill);return true}if(!placeCloud()){const observer=new MutationObserver(()=>{if(placeCloud())observer.disconnect()});observer.observe(document.body,{childList:true})}})();
